### ISSUE TITLE
Doesn't work with empty API keys

### ISSUE THREAD

**Issue by ReWard0101** [chigkim/Ollama-MMLU-Pro#2]
When using LM Studio there is no API key, and leaving 

`api_key = ""`

results in a Connection Error.

When I host the LLM with koboldcpp and add an API key it works.

**Comment by ReWard0101** [comment]
It does work if I use a dummy api_key, like
`api_key = "test123"`

while 
`api_key = ""` 

still results in a connection error.

**Comment by chigkim** [comment]
Cool, please use dummy key for now.
