### ISSUE TITLE
Bug: More robust extraction regex than official Tigerlabs mmlu-pro

### ISSUE THREAD

**Issue by netanel-haber** [chigkim/Ollama-MMLU-Pro#6]
Their code:
https://github.com/TIGER-AI-Lab/MMLU-Pro/blob/main/evaluate_from_api.py#L200

Your code:
https://github.com/chigkim/Ollama-MMLU-Pro/blob/main/run_openai.py#L239

Notice your code allows optional parens around the answer:
`answer: (D)`

While tigerlabs would fail this.

This theoretically can inflate hits in comparison with official leaderboard results (even if it may be more "correct" on first principles).

**Comment by chigkim** [comment]
Not sure they still do, but when I forked, tiger labs had different methods for different models from system prompt to regex patterns for answer extraction.

https://www.reddit.com/r/LocalLLaMA/comments/1dw8l3j/why_does_mmlu_pro_use_different_parameters_and/

I had a discussion with them about that. They told me that it only has minor impact.

I posted my result here.

https://www.reddit.com/r/LocalLLaMA/comments/1e4eyoi/mmlu_pro_how_different_parameters_and_regex/
